### ISSUE TITLE
Uncaught TypeError: ev.getEditor is not a function

### ISSUE THREAD

**Issue by jellymann** [jacogr/atom-lcov-info#30]
[Enter steps to reproduce below:]

1. open a file
2. toggle lcov-info
3. close the file
4. open a different file

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [lcov-info](https://github.com/jacogr/atom-lcov-info) package, v0.10.4

### Stack Trace

Uncaught TypeError: ev.getEditor is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: ev.getEditor is not a function
  at /Users/daniel/.atom/packages/lcov-info/lib/lcov-info-view.coffee:24:64
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:313:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -2:59.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:58.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:55.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:55.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:53.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:49.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:49.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:48.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:45.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:45.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:45 core:save (atom-text-editor.editor.is-focused)
     -0:55.5.0 lcov-info:toggle (atom-text-editor.editor.is-focused)
  3x -0:16.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  2x -0:02.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "coffee-autocompile",
      "vim-mode"
    ],
    "projectHome": "/Users/daniel/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
autocomplete-ruby, v0.1.0
change-case, v0.6.0
coffee-compile, v0.16.1
file-icons, v1.5.8
language-glsl, v2.0.1
language-jade, v0.5.1
lcov-info, v0.10.4
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-eslint, v3.0.2
linter-ruby, v0.1.6
ruby-block, v0.3.4
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by Toff9** [comment]
This issue is related to #26.

See my PR #28 to fix it.
