### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by jellymann** [jacogr/atom-lcov-info#31]
[Enter steps to reproduce below:]

1. Toggle lcov-info
2. Click on the "coverage" header in the lcov-info panel to try sort list by coverage

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [lcov-info](https://github.com/jacogr/atom-lcov-info) package, v0.10.5

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/daniel/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:84

TypeError: Cannot read property '1' of undefined
  at Object.Tablesort.sortTable (/Users/daniel/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:84:63)
  at HTMLTableCellElement.onClick (/Users/daniel/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:38:22)

```

### Commands

```
  2x -1:35.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:34.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:34.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:32.7.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -1:32.5.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -1:32 core:move-left (atom-text-editor.editor.is-focused)
     -1:30.9.0 editor:add-selection-above (atom-text-editor.editor.is-focused)
     -1:30.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:30.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:30 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:29.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:28.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  2x -1:28.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:27.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "coffee-autocompile",
      "vim-mode"
    ],
    "projectHome": "/Users/daniel/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
autocomplete-ruby, v0.1.0
change-case, v0.6.0
chester-atom-syntax, v0.1.1
coffee-compile, v0.19.0
file-icons, v1.6.9
language-glsl, v2.0.1
language-jade, v0.6.2
lcov-info, v0.10.5
linter, v1.8.1
linter-coffeelint, v1.1.0
linter-eslint, v3.1.1
linter-ruby, v1.2.0
preview, v0.16.3
ruby-block, v0.3.5
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by Toff9** [comment]
These issue is present since atom version 1.0.12.
https://github.com/atom/atom/releases/tag/v1.0.12
