### ISSUE TITLE
Failed to activate the lcov-info package

### ISSUE THREAD

**Issue by Gerhardk** [jacogr/atom-lcov-info#32]
1. Toggle lcov

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [lcov-info](https://github.com/jacogr/atom-lcov-info) package, v0.10.5

### Stack Trace

Failed to activate the lcov-info package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'coverage-table-row'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'coverage-table-row'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/gerhardk19/.atom/packages/lcov-info/lib/panel-row.coffee:72:29)
    at Object.<anonymous> (/Users/gerhardk19/.atom/packages/lcov-info/lib/panel-row.coffee:77:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/gerhardk19/.atom/packages/lcov-info/lib/panel.coffee:6:14)
```

### Commands

```
     -0:03.4.0 lcov-info:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-jade"
    ],
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-jade, v0.3.0
autocomplete-ruby, v0.1.0
chester-atom-syntax, v0.1.1
coverage, v0.6.1
file-icons, v1.6.11
language-slim, v0.5.0
lcov-info, v0.10.5
linter, v1.9.1
linter-coffeelint, v1.1.2
linter-eslint, v3.1.1
linter-jade, v0.3.2
linter-ruby, v1.2.0
pretty-json, v0.4.1
rspec-snippets, v0.4.0
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by lslezak** [comment]
The crash is caused by a conflict with the **coverage** Atom package. So either wait until the fix in #35 is released or as a workaround you can uninstall the **coverage** package.
