### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by skarfacegc** [jacogr/atom-lcov-info#36]
[Enter steps to reproduce below:]

1. create lcov (using istanbul)
2. toggle lcov
3. click sort

Sample of the report  (column alignment is pretty close in example)
Test Coverage               Coverage         Percent   Lines    Hits/line
<filename>   ========= 100%   13/13  4.08  

Percent/coverage are misaligned, looks like what's in the percent column is actually the hits/line data.
Lines is missing entirely.  Test Coverage is the label for the filename

Looks like something is odd between the columns and the headers.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [lcov-info](https://github.com/jacogr/atom-lcov-info) package, v0.10.5

### Stack Trace

Uncaught TypeError: Cannot read property '2' of undefined

```
At /Users/x/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:84

TypeError: Cannot read property '2' of undefined
    at Object.Tablesort.sortTable (/Users/x/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:84:63)
    at HTMLTableCellElement.onClick (/Users/x/.atom/packages/lcov-info/node_modules/tablesort/src/tablesort.js:38:22)
```

### Commands

```
     -0:19.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.3.0 lcov-info:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Users/x/Development"
  }
}
```

### Installed Packages

```coffee
# User
fonts, v1.0.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
jsonlint, v1.1.2
lcov-info, v0.10.5
linter, v1.11.3
linter-jshint, v1.2.1
minimap, v4.18.4
sync-settings, v0.6.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by skarfacegc** [comment]
looks like this may be a dup of #31
